#!/bin/bash
set -ex

docker_compose_down() {
    docker-compose down -v
}
trap docker_compose_down EXIT

docker-compose up -d mysql
docker-compose logs mysql
docker ps -a
docker-compose run ci make all
