#!/usr/bin/env bash

set -ex

: ${GOSSIP_LOGFILE:="/usr/local/log/gossip.log"}
: ${GOSSIP_BINARY:="/usr/local/bin/gossip"}
: ${GOSSIP_PIDFILE:="/var/run/gossip.pid"}
: ${GOSSIP_AUTH_TOKEN:=some-token}
: ${GOSSIP_DB_USERNAME:=root}
: ${GOSSIP_DB_PASSWORD:=some-password}
: ${GOSSIP_DB_DBNAME:=witness}

script/install

if test -f ".env"; then
  source .env
fi

sudo PORT=7483 \
  GOSSIP_AUTH_TOKEN="${GOSSIP_AUTH_TOKEN}" \
  GOSSIP_DB_DBNAME="${GOSSIP_DB_DBNAME}" \
  GOSSIP_DB_USERNAME="${GOSSIP_DB_USERNAME}" \
  GOSSIP_DB_PASSWORD="${GOSSIP_DB_PASSWORD}" \
  daemonize \
  -e ${LOGFILE} \
  -o ${LOGFILE} \
  -a \
  -p ${PIDFILE} \
  -l /var/lock/subsys/gossip \
  -u nobody \
  ${BINARY}
