#!/bin/bash
. .env
mkdir -p data

set -x
make docker && clear && docker run -it --rm \
    --publish $PORT:$PORT \
    --volume $(pwd)/data:/data:rw \
    --env GOSSIP_DB_PATH=/data/gossip.sqlite3 \
    --env GOSSIP_AUTH_TOKEN=$GOSSIP_AUTH_TOKEN \
    parkr/gossip \
    gossip -bind=:$PORT
