#! /bin/bash

set -e

source .env

access() {
  echo "$3 GET /api/messages/$1"
  echo "==============================="
  time curl -i http://localhost:7483/api/messages/$1$2
  echo
  echo "-------------------------------"
  echo
}

post() {
  echo "$3 POST /api/messages/$1"
  echo "==============================="
  time curl -i -X POST -d "$4" http://localhost:7483/api/messages/$1$2
  echo
  echo "-------------------------------"
  echo
}

unauthorized_post() {
  post "$1" "" "Unauthorized" "$2"
}

authorized_post() {
  post "$1" "?access_token=$GOSSIP_AUTH_TOKEN" "Authorized" "$2"
}

unauthorized_access() {
  access "$1" "" "Unauthorized"
}

authorized_access() {
  access "$1" "?access_token=$GOSSIP_AUTH_TOKEN" "Authorized"
}

DATE=$(date +"%a, %d %b %Y %T %Z")

authorized_post   "log" "room=%23jekyll&author=parkr&message=hey,%20yall&time=${DATE}"
authorized_access "latest"
authorized_access "1"

unauthorized_access "latest"
unauthorized_access "1"
