#!/bin/bash

set -e

# Make sure we have the correct gom path.

cd $(dirname "$0")/..

# Run the tests

if test -z "$1"; then
  dir="."
else
  dir="$1"
fi

echo "==> Running tests in '${dir}'"
pushd $dir > /dev/null
(test -z $(go fmt) && echo -e "PASS\tgo fmt passed.") || (echo -e "FAIL\tgo fmt failed." && exit 1)
TZ=UTC go test -cover
go vet || (echo -e "FAIL\tgo vet failed." && exit 1)
popd > /dev/null
